### ISSUE TITLE
Download problems: just creates empty folder

### ISSUE THREAD

**Issue by thejsa** [DownloadMii/DownloadMii-3DS#24] opened 2015-02-03 19:31 UTC
When I download things from DownloadMii it just creates an empty folder with the app's name in sdmc:/3ds/.

Is this because it hasn't fully downloaded? If so it would help to have some sort of progress bar. Perhaps it could also just save the program directly to the SD as a ZIP?

**Comment by filfat** [comment] 2015-02-04 21:23
progressbar is planned (#14). Do you receive any kind of crash or hang while downloading apps?

**Comment by thejsa** [comment] 2015-02-05 14:39
Sometimes... not sure exactly how it's caused.

On 04/02/2015, Filiph Sandström <notifications@github.com> wrote:
> progressbar is planned (#14). Do you receive any kind of crash or hang while
> downloading apps?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-72942274


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by celcodioc** [comment] 2015-02-07 13:26
I'm looking into it, I believe it's caused by DownloadMii downloading binaries from HTTPS addresses. If that's the case, a fix should be ready soon.

**Comment by purpasmart96** [comment] 2015-02-08 01:14
I'm getting the same issues described here, even when updating DownloadMii itself. It never actually updates, it returns to the Homebrew launcher thus me thinking it was updated but when I enter DownloadMii after it exits it acts like was never updated at all...

**Comment by filfat** [comment] 2015-02-08 11:04
celcodioc hmm

**Comment by filfat** [comment] 2015-02-08 11:04
@celcodioc hmm

**Comment by celcodioc** [comment] 2015-02-08 19:48
Upon closer examination I've found that you can't download anything (as far as I can tell) from `installApp`, and the httpcOpenContext error code is -660561894, but I don't know what that means.

Everything works in 3dmoo, but not on an actual 3DS. :/

**Comment by thejsa** [comment] 2015-02-09 16:17
Ask smea?

Maybe try forcing non-HTTPS on the server?

On 08/02/2015, celcodioc <notifications@github.com> wrote:
> Upon closer examination I've found that you can't download anything (as far
> as I can tell) from `installApp`, and the httpcOpenContext error code is
> -660561894, but I don't know what that means.
>
> Everything works in 3dmoo, but not on an actual 3DS. :/
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-73427866


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by filfat** [comment] 2015-02-10 19:54
@celcodic the error is apparently "Session closed by remote". hmmm

**Comment by thejsa** [comment] 2015-02-11 15:37
So your server has closed the connection...
Is that when using HTTPS? If so I'd suggest disabling HTTPS
server-side and changing the 3DS code to use HTTP.

On 10/02/2015, Filiph Sandström <notifications@github.com> wrote:
> @celcodic the error is apparently "Session closed by remote". hmmm
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-73771207


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by filfat** [comment] 2015-02-11 18:20
We don't use HTTPS for the api stuff, only for the website as SSL doesn't quite work on the 3DS yet :/

Im guessing its either something with newApi or a change on azure; the first one is probably the reason.

Sent from Windows Phone 8.1 on the Nokia Lumia 920
________________________________

**Comment by filfat** [comment] 2015-02-11 19:39
@celcodioc Maybe we should switch back to the old API? Or you can see what might be causing it in the new API?

**Comment by celcodioc** [comment] 2015-02-11 19:44
@filfat It's not the new API. I tried with an old app, libctru and website version (from January 11). Same problem there. However it looks like something like https://github.com/smealum/ctrulib/issues/66 is happening, so I'm going to go back to the latest version and check that now.

**Comment by celcodioc** [comment] 2015-02-11 20:13
Yup. Seems like that is the issue. The eighth `httpcOpenRequest` errors with -660561894 (0xd8a0a01a).

**Comment by filfat** [comment] 2015-02-11 20:31
So its not on our end then. However it looks like they fixed it 10 days ago? :/

Sent from Windows Phone 8.1 on the Nokia Lumia 920
________________________________

**Comment by thejsa** [comment] 2015-02-12 14:40
Solved then?

On 11/02/2015, Filiph Sandström <notifications@github.com> wrote:
> So its not on our end then. However it looks like they fixed it 10 days ago?
> :/
>
> Sent from Windows Phone 8.1 on the Nokia Lumia 920
> ________________________________
> From: celcodioc<mailto:notifications@github.com>
> Sent: ‎2015-‎02-‎11 21:13
> To: DownloadMii/DownloadMii<mailto:DownloadMii@noreply.github.com>
> Cc: Filiph Sandström<mailto:filfat@hotmail.se>
> Subject: Re: [DownloadMii] Download problems: just creates empty folder
> (#24)
>
> Yup. Seems like that is the issue. The eighth `httpcOpenRequest` errors with
> -660561894 (0xd8a0a01a).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-73955600
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-73958677


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by filfat** [comment] 2015-02-16 01:34
celcodioc does it still fail with the latest ctrulib commit?

**Comment by filfat** [comment] 2015-02-20 18:19
Alright, it doesn't work. I will look for memory leaks and handles that are left open asap.

What we know so far:
* The screen suddenly started flickering.
* It crashes when it tries to download an app, where exactly is currently unknown.

We could code something quick to log everything to a log file on the SD card.

**Comment by purpasmart96** [comment] 2015-02-20 22:28
Yeah the screen is now flickering...

**Comment by filfat** [comment] 2015-02-20 22:59
could somebody please test this build: http://www.filedropper.com/downloadmii and report back with the file created at the root or the sdcard named "downloadmii.log" thanks :)

**Comment by purpasmart96** [comment] 2015-02-21 00:55
<code>
DownloadMii Build: Feb 20 2015

Loading...

networkInit: started...

Network connection is active!

Getting remote api version

1.2.0.0


Getting DownloadMii version...

/3ds/3dscraft

/3ds/blargSnes

/3ds/cubedemo

/3ds/ftpony

/3ds/gameyob

/3ds/yeti3DS

/3ds/3dsgba

/3ds/blargSnes_unstable

/3ds/3dsutils-dump

/3ds/downloadmii

/3ds/data_collector

/3ds/3ds_homemenu_extdatatool

/3ds/playcoin

/3ds/citragb

httpcOpenContext returned 0

Download Size2: 15439, Size: 15439


 
Pong 3DS 
ORGANIZ3D 
CHMM 
DownloadMii 
3DS Tic Tac Toe 
blargSnes 
Piano Training for 3DS 
Fantasy Life Save extractor 
3DSurfer 
3DText 
Useless Homebrew 
PixelRoad 
3DS Hangman 
3DSCraft 
Quick Reboot 
World of 3DSand 
3DSnake 
Fact Crow 
3DS Pong 
Timer 
3dsmandelbrot 
ftbrony 
3DS Paint 
2048 3D 
Bounce test 
Guess the number 


httpcOpenContext returned 0

Download Size2: 15439, Size: 15439


 
DownloadMii 
3dsmandelbrot 
3DS Paint 
3DSnake 
blargSnes 
Quick Reboot 
2048 3D 
ORGANIZ3D 
3DS Pong 
Playcoin Setter 
3DSCraft 
ftbrony 
CHMM 
World of 3DSand 
Guess the number 
Fact Crow 
Bounce test 
Timer 
Useless Homebrew 
3DSurfer 
3DS Tic Tac Toe 
3DText 
3DS Hangman 
PixelRoad 
Piano Training for 3DS 
Fantasy Life Save extractor 


httpcOpenContext returned 0

Download Size2: 1985, Size: 1985


 
DownloadMii 


httpcOpenContext returned 0

Download Size2: 23, Size: 23

Error: Not implemented!

updateAppList(4): Error

httpcOpenContext returned 0

Download Size2: 274, Size: 274

 
Games 
Media 
Utilities 
Emulators 
Hello World-ishs 
Other 


httpcOpenContext returned 0

Download Size2: 7, Size: 7

Downloading banner...

httpcOpenContext returned 0

Download Size2: 230400, Size: 230400

Banner downloaded!

All init done, entering main loop!

Input, 1

Input, 2

Input, 3

Input, 4

Input, 5

Input, 6

Input, 7

Input, 8

Input, 9

Input, 10

Input, 11

Input, 12

Input, 13

Input, 14

Input, 15

Input, 16

Input, 17

Input, 18

Input, 19

Input, 20

Input, 21

Input, 22

Input, 23

Input, 24

Input, 25

Input, 26

Input, 27

Input, 28

Input, 29

Input, 30

Input, 31

Input, 32

Touch: 259 201

Input, 33

Touch: 262 203

Input, 34

Input, 35

Input, 36

Input, 37

Input, 38

Touch: 169 188

Input, 39

Touch: 180 199

Input, 40

Touch: 261 181

Input, 41

Input, 42

Input, 43

Input, 44

Input, 45

Touch: 260 108

Button(1) Pressed.

Input, 46

Touch: 218 210

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Button(0) Pressed.

Input, 47

Installing App..

httpcOpenContext returned -660561894

error: httpcOpenContext
</code>

**Comment by filfat** [comment] 2015-02-22 22:21
can you test http://build.filfatstudios.com:8080/job/DownloadMii%20(3DS)/lastSuccessfulBuild/artifact/DownloadMii.3dsx Thanks :)

**Comment by purpasmart96** [comment] 2015-02-23 00:53
@filfat This build worked a bit better
DownloadMii Build Date: Feb 23 2015

Configuring network...

A network connection is active!

Getting remote API version

Getting DownloadMii version...

Populating app lists...

updateAppList(1): Started...

Download size: 15440

updateAppList(2): Started...

Download size: 15440

updateAppList(3): Started...

Download size: 1986

updateAppList(4): Started...

Download size: 23

error: Faulty json "Error: Not implemented!"

updateAppList(4): Error

updateAppList(5): Started...

Download size: 274

App lists populated!

Download size: 8

Configuring banner...

Download size: 230400

Banner configured!

Everything configured, entering main loop!

Installing app "blargSnes"..

Downloading 3dsx file...

Download size: 64

3dsx: http://dmii.blob.core.windows.net/3dsx/cPqnRortpGNvECA4FMmL7T8h

Download size: 838696

3dsx downloaded!

Downloading smdh file...

Download size: 64

Download size: 14016

smdh downloaded!

Saving 3dsx file...

3dsx saved

Saving smdh file...

smdh saved

VERSION saved

No appdata found

App installation completed!

updateAppList(1): Started...

Download size: 15440

updateAppList(2): Started...

Download size: 15440

updateAppList(3): Started...

Download size: 1981

updateAppList(4): Started...

Download size: 23

error: Faulty json "Error: Not implemented!"

updateAppList(4): Error

updateAppList(5): Started...

Download size: 274

Installing app "3DS Tic Tac Toe"..

Downloading 3dsx file...

Download size: 64

3dsx: http://dmii.blob.core.windows.net/3dsx/pKyaDBxhILTbCiJ18A9PjNn6

Download size: 966156

3dsx downloaded!

Downloading smdh file...

Download size: 64

Download size: 14016

smdh downloaded!

Saving 3dsx file...

3dsx saved

Saving smdh file...

smdh saved

VERSION saved

No appdata found

App installation completed!

updateAppList(1): Started...

Download size: 15440

updateAppList(2): Started...

Download size: 15440

updateAppList(3): Started...

Download size: 1981

updateAppList(4): Started...

Download size: 23

error: Faulty json "Error: Not implemented!"

updateAppList(4): Error

updateAppList(5): Started...

Download size: 274

Installing app "ORGANIZ3D"..

Downloading 3dsx file...

Download size: 64

3dsx: http://dmii.blob.core.windows.net/3dsx/Fd9iAD2t8NG3Q1SBYzmvwKrl

Download size: 1080532

3dsx downloaded!

Downloading smdh file...

Download size: 64

Download size: 14016

smdh downloaded!

Saving 3dsx file...

3dsx saved

Saving smdh file...

smdh saved

VERSION saved

Downloading and unzipping appdata... 
Download size: 67

Download size: 283549

error opening ZIP file.

Error with zipfile in ZitGlobalInfo

**Comment by linoma** [comment] 2015-02-23 06:38
Maybe the file is corrupted because the server's connection is close. You can try restart download with http header like RANGE http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35

**Comment by thejsa** [comment] 2015-02-23 17:06
I'll try and test this today, from my web dev's perspective it looks
like a server issue

On 23/02/2015, Lino <notifications@github.com> wrote:
> Maybe the file is corrupted because the server's connection is close. You
> can try restart download with http header like RANGE
> http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/24#issuecomment-75495236


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by filfat** [comment] 2015-04-06 13:06
I will close this as itseems to be working in the latest release.

**Closed by filfat** 2015-04-06 13:06 UTC
Labels: bug
